name: 'Get & Cache Dependencies'
description: 'Get and cache dependencies'
runs:
  using: 'composite' #here must be 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash #if 'run' key is used, then 'shell' key is required
