## here the workflow is triggered when a new issue is opened.
## the workflow outputs info about this event

name: Output information
on: [workflow_dispatch]
#  issues:
#    types: [opened]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub event info
        run: echo "${{ toJSON(github.event) }}"