name: Reusable workflow

#here we specify this trigger as we want to use this workflow as part of a job in another workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    #outputs: #output can be set here to be used somewhere else
    #  result:
    #   description: The result of the deployment operation
    #    value: ...
    #secrets:
    #  some-secret:
    #    required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Deploy
        run: echo "Deploying..."