name: Matrix Demo
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include: # this include part tells to run exactly this single combination
          - node-version: 18
            operating-system: ubuntu-latest
        exclude: # this exclude part tells NOT to run exactly this single combination
          - node-version: 12
            operating-system: ubuntu-latest
    runs-on: ${{ matrix.operating-system }} #here we refer to the matrix above and we say that the job should run 2 times on 2 different systems (in this case). Jobs will run in parallel.
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build

# NOTE: as a result this job will run for all combinations of the matrix.